### ISSUE TITLE
URLs within module docs don't work the same for all outputs

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#103]
Currently for module docs, we say we support a [few different options](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#linking-and-other-format-macros-within-module-documentation). The problem is - not every output supports these options.

The outputs are:
- docs.ansible.com
-  `ansible-doc` cli command
-  GalaxyNG/AH
- Private GalaxyNG/AH
-  ansible-navigator
- vscode plugin
- possibly ansible language server

We also used to support direct links in `ansible-doc` output that are URLS the user could copy and paste into a browser and get  the link for  the specific version of ansible they were running. We lost this capability as well.

**Comment by samccann** [comment]
Currently we say we support:

- L() for links with a heading. For example: See L(Ansible Automation Platform,https://www.ansible.com/products/automation-platform). As of Ansible 2.10, do not use L() for relative links between Ansible documentation and collection documentation.

- U() for URLs. For example: See U(https://www.ansible.com/products/automation-platform) for an overview.

- R() for cross-references with a heading (added in Ansible 2.10). For example: See R(Cisco IOS Platform Guide,ios_platform_options). 

- M() for module names. For example: See also M(ansible.builtin.yum) or M(community.general.apt_rpm).

Relative support levels:
- docs.ansible.com - M() and R() preferred. L() and U() work, but will become bad links if pages move.
- ansible-doc - M() is stripped from the output so it's not a link, just the name of the module. L() doesn't create a copy-able link. U() works but will only point to /latest/ docs as a copyable link. R() gets stripped out, leaving text that makes no sense to the end user.
- Galaxy/NG (AH) - M() is stripped so there is no clickable link. U() works but becomes a broken link if a page moves. L() with an absolute URL works. L() with relative links - can't find an example as most collections seem to have replaced these with U(). Don't know an R() example that exists on AH to verify.

**Comment by samccann** [comment]
Note: Galaxy links probably can't support M() because some of those would exist in collections not on galaxyNG (such as ansible.builtin.)

**Comment by felixfontein** [comment]
semantic markup adds support for `P()`, `O()`, and `RV()`, which allows to link to other plugins (than modules), options, and return values as well.

About Galaxy: it can also support `M()` in most cases. With a little extra logic, it can also support ansible.builtin by converting `M(ansible.builtin.foo)` to a link to `https://docs.ansible.com/ansible/latest/collections/ansible/builtin/foo_module.html`.

**Comment by samccann** [comment]
Private instances of GalaxyNG/AH may pose unique problems as any solution can't 'hard docs/mapp them'. When we limited to docs/galaxy.ansible.com and cloud.redhat.com/ah/ .... we can make some optimizations.
when you add privateFoo/ansible/blalbala that makes it harder.
