### ISSUE TITLE
Collection Requirements: update based on discussion in community-topics

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#106]
https://github.com/ansible-collections/overview/pull/220
based on https://github.com/ansible-community/community-topics/issues/152#issuecomment-1293260128

**Comment by samccann** [comment]
This one seems to be done by the PR in  the main description?

**Comment by Andersson007** [comment]
>This one seems to be done by the PR in the main description?

yep, thanks, closing as complete
