### ISSUE TITLE
Clarify documentation for community collection testing

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-team#109]
From Matrix, it looks like the docs for testing community collections is unclear, fragmented, and out of date. Purpose of this task is to work with the community folks to clarify things and ensure documentation supports community collection maintainers.

[Is this still something applicable nowadays ? https://docs.ansible.com/ansible/latest/dev_guide/testing_units_modules.html#traps-for-maintaining-python-2-compatibility](https://matrix.to/#/!HJtetIFWYEIDBOXxFE:libera.chat/$fLQ5DYcSKLBWgbXOTYBBIoLmmt9Um1VEab7DUqFSO2E?via=ansible.com&via=libera.chat&via=matrix.org)

**Comment by Andersson007** [comment]
To collect related stuff:
- https://github.com/ansible-community/community-topics/issues/156
- [Integration testing quick-start guide](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_integration_tests.html)
- [Unit testing quick-start guide](https://github.com/ansible/community-docs/blob/main/unit_tests_quick_start_guide.rst)
- [Local PR testing guide](https://github.com/ansible/community-docs/blob/main/test_pr_locally_guide.rst)
- [Maintainer guidelines](https://docs.ansible.com/ansible/devel/community/maintainers_guidelines.html) does not contain any info about testing and CI ! After the testing docs are updated/created/re-arranged, we should add links to the guidelines.

**Comment by Andersson007** [comment]
TODO contain a list of docs (old) related to ansible testing in general:
- ...

**Comment by oraNod** [comment]
Moved to https://github.com/ansible/ansible-documentation/issues/1688
