### ISSUE TITLE
ansible-inclusion repository: tidy up discussions

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#11]
Go through and tidy up discussions in the [ansible-inclusion](https://github.com/ansible-collections/ansible-inclusion/) repository.

Along the way:
- Create a new category for inclusion requests where maintainers feedback is needed but they don't respond. Name it as `Maintainers feedback needed` or `Maintainers do not respond`.
- Ping maintainers if they are still interested in continuing the process or if there are any obstacles they can't overcome.
- Ping reviewers.
- Update categories.

**Comment by samccann** [comment]
@Andersson007 is this still an active issue or can we close it?

**Comment by Andersson007** [comment]
@samccann we will solve it in reduce fragmentation epic, so closing this one, thanks
