### ISSUE TITLE
Find community maintainers for the Ansible Sphinx theme

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-team#110]
From the DaWGs meeting we discussed getting a group of community maintainers for the Sphinx Ansible theme.

**Comment by Andersson007** [comment]
i can recall the following things that can be leveraged:
- Bullhorn:)
- Announcing in community meetings using `#info `
- Mailing lists

**Comment by samccann** [comment]
Closing in favor of https://github.com/ansible-community/community-team/issues/183
