### ISSUE TITLE
Define documentation needs for Galaxy vs GalaxyNG

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#116]
Current estimates is GalaxyNG will go GA around April/May 2023 timeframe (still guestimate).

We currently have galaxy-related docs on the Ansible project docsite for a[ Galaxy user guide](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html) and [Galaxy developer Guide](https://docs.ansible.com/ansible/latest/galaxy/dev_guide.html).

We need to:

- [x] Evaluate both to determine if they are still accurate and needed (most is reused content from the collection user and developer guides).
- [x] Determine what sort of presence GalaxyNG should have on the Ansible project docs. (that is, besides the current link on the ecosystem page).
- [x] Determine how best to cover both galaxy and galaxyNG (if at all ) on the Ansible project docs at docs.ansiblecom/ansible.

Related to https://github.com/ansible-community/community-team/issues/53

**Comment by samccann** [comment]
private issue test - https://github.com/ansible-community/community-team/issues/116

**Comment by samccann** [comment]
Feedback from @rochabruno after initial review:

```
 reviewed both pages and 99% are accurate on the new galaxy, all the CLI and Collection development guidelines are still compatible.

I think we can keep those pages and update the outdated parts,
everything about roles can be removed and the parts guiding through Galaxy UI needs updates.
```

**Comment by samccann** [comment]
Since the content remains mostly accurate, the next point to decide - do we really need all the CLI and collection dev guidelines repeated in the Galaxy guides, or should we just point to them? The are reused content, but it trips up contributors to add content to the snippet files and chances are,  they are no longer in sync.

**Comment by oraNod** [comment]
@samccann Pointers in some kind of reference section would get my vote.

**Comment by samccann** [comment]
https://github.com/ansible/ansible-documentation/pull/145 - removes the repeat content and replaces with the link.

**Comment by samccann** [comment]
Closing in favor of a direct issue on the docs repo - https://github.com/ansible/ansible-documentation/issues/146
