### ISSUE TITLE
Announce collection contributor docs recently moved to docs.ansible.com via available sources

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#12]
Announce docs moved from [community-docs](https://github.com/ansible/[community-docs](https://github.com/ansible/community-docs/) to [docs.ansible.com](https://docs.ansible.com/ansible/devel/community/contributor_path.html).

Why: we have those important contributor docs on our site but many people don't know about it so can't use.

- [ ] Write a good announcement covering all the docs
- [ ] Publish it via:
- [ ] Bullhorn (at least)
- [ ] (maybe) reddit
- [ ] other sources (please suggest other sources if you have something on your mind)

**Comment by samccann** [comment]
The move happened some time ago so closing this issue now... thanks!
