### ISSUE TITLE
Docsite user/contributor improvement, personas

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#120]
- https://github.com/ansible-community/community-topics/issues/175
- https://hackmd.io/pZb5w5JFRQW3RJ73n23tlw?both#/
- https://www.mindmeister.com/map/1840534336?t=WIqBlrv8ee
- https://www.mindmeister.com/map/2567970572
- https://www.mindmeister.com/map/2568078020

**Comment by samccann** [comment]
Initial journeys for personas presented as milestones with https://github.com/ansible/docsite/pull/140

**Comment by Andersson007** [comment]
Thanks, my feedback is in
- https://github.com/ansible/docsite/pull/142
- https://github.com/ansible/docsite/pull/143
- will discuss it with Don today in 1:1

**Comment by samccann** [comment]
@Andersson007 @oraNod - I think this is done? We'll of course adapt with feedback etc but I think we are defined and have the prototype set up with these (and tracking further needs in that repo).
