### ISSUE TITLE
Investigate moving community-ee ownership to community members

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#143]
Currently, the community-ees on quay are not keeping pace with core releases. Would be good if we could get these updatable by community volunteers.

https://quay.io/repository/ansible/ansible-runner?tab=tags&tag=latest

and also 

https://quay.io/repository/ansible/ansible-builder?tab=tags&tag=latest

**Comment by samccann** [comment]
This may have a greater impact if we do get an increased number of community members wanting to use 
 - can community members push items to quay or do we need to host them somewhere more accessible to community members?

**Comment by leogallego** [comment]
With the release of Ansible Builder 3.0 the above repos have been deprecated:

From ansible-builder quay: https://quay.io/repository/ansible/ansible-builder?tab=info

> This Repository is Deprecated
> With the release of [Ansible Builder 3.0](https://ansible-builder.readthedocs.io/en/stable/) and its ability to create Ansible Execution Environments from many different "stock" container images, the ansible-builder container images are no longer necessary. The contents of this repository are deprecated and will no longer be maintained.

From ansible-runner quay: https://quay.io/repository/ansible/ansible-runner?tab=info

> This repository is no longer maintained. Consider using [ansible-builder](https://github.com/ansible/ansible-builder) >= 3.0 to ease creation of your own container image with Ansible Runner and Core.

We also announced the [community EEs in 2023](https://forum.ansible.com/t/execution-environments-getting-started-guide-community-ee-images-availability/1341). These new EEs should be community managed. @Andersson007 or @anweshadas can confirm if they are handled by the [EE group](https://forum.ansible.com/g/ExecutionEnvs?asc=true) or the [Release Managers group](https://forum.ansible.com/g/release-managers?asc=true) in the forum, or if that is still in process.
