### ISSUE TITLE
docsite, how can I help: add community topics and steering committee info

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#146]
https://docs.ansible.com/ansible/devel/community/how_can_I_help.html#how-can-i-help

Something similar to what we have in https://docs.ansible.com/ansible/devel/community/contributor_path.html

**Comment by samccann** [comment]
Related to https://github.com/ansible-community/community-team/issues/147

**Comment by samccann** [comment]
Issue (both) should be moved to ansible/ansible as its a docs issue in that repo
