### ISSUE TITLE
Docsite: think of merging How Can I Help and the Contributor path

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#147]
As there are a lot of intersections, we should think of merging:
- https://docs.ansible.com/ansible/devel/community/how_can_I_help.html#how-can-i-help
- https://docs.ansible.com/ansible/devel/community/contributor_path.html

**Comment by samccann** [comment]
Related to https://github.com/ansible-community/community-team/issues/146

**Comment by samccann** [comment]
This should be moved to ansible/ansible as it's a docs issue on that docset.

**Comment by Andersson007** [comment]
> This should be moved to ansible/ansible as it's a docs issue on that docset.

Currently it's just an idea not necessarily worthwhile. The goal of this is not to forget to take a look and think.
