### ISSUE TITLE
Plan Ansible Community Day at Summit

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#158]
Need to gather proposals internal and external for the upcoming community day in Boston, MA.

**Comment by cybette** [comment]
External proposals to be gathered at: https://hackmd.io/@ansible-community/ACD2023-Boston

**Comment by cybette** [comment]
Agenda confirmed and updated at https://hackmd.io/@ansible-community/ACD2023-Boston

Swag ordered and in production

Registration will be to add the event in the [session catalog](https://events.experiences.redhat.com/widget/redhat/sum23/SessionCatalog2023/session/1678832216982001yETF) to one's schedule when they have registered for Red Hat Summit. Currently there's a waitlist.
