### ISSUE TITLE
Set up github repo for community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#165]
We need to:

- [x] Decide which github org to use (ansible, ansible-community, someplace else?)
- [x] Set up the shell for this new repo, including base files such as readme, contributing and a pointer to our [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).

**Comment by samccann** [comment]
We will go with the ansible-community Org.

**Comment by cybette** [comment]
Repo created at https://github.com/ansible-community/community-website

**Comment by samccann** [comment]
We still need a CONTRIBUTING.md file and then this issue is done I think?

**Comment by cybette** [comment]
pending decision on [license](https://github.com/ansible-community/community-website/issues/3) as well

**Comment by samccann** [comment]
Fixed by https://github.com/ansible-community/community-website/pull/4
