### ISSUE TITLE
Docs: is there a consistent doc how to make a new collection up and running?

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#17]
Docs: is there a consistent doc under https://docs.ansible.com/ansible/devel/community about how to make a new collection up and running?

If not create it.

Among other thing should cover:
- Request to create a skeleton / move a repo under the ansible-collections org
- Setup CI (AZP / GHA)
- Automated publishing on Galaxy via Zuul
- ...

**Comment by Andersson007** [comment]
The following email to one of partners can be used:

You can use the following sources:

- the [collection_template](https://github.com/ansible-collections/collection_template/)  repository to create a collection skeleton for your collection. You can create it in your org repo or under https://github.com/ansible-collections/ (in this case, create an issue in the [overview](https://github.com/ansible-collections/overview) repo with a request to create a new repo)
- the Collection [development guidelines](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html).
- the Collection [requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst) to make your collection satisfying them from the beginning (there's also a shorter version aka the Collection [checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md)) that can be helpful for inclusion to Ansible in the future
- when developing your modules and plugins follow the best practices described in https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html and https://docs.ansible.com/ansible/devel/dev_guide/style_guide/index.html
- you can maintain you collection following https://docs.ansible.com/ansible/devel/community/maintainers.html, in particular you can be interested in [releasing](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_releasing.html) 
- the [Integration testing guide](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_integration_tests.html) and [Unit testing guide](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_unit_tests.html) to cover your collection with tests
- you can find examples of collection repositories currently included in the ansible package within the [ansible-collections](https://github.com/ansible-collections) repo, e.g. https://github.com/ansible-collections/community.dns
- when your collection satisfies the Collection requirements mentioned above, you can submit it for inclusion in the ansible package by creating a discussion in the [ansible-inclusion](https://github.com/ansible-collections/ansible-inclusion/discussions/) repo (read its README first)

**Comment by Andersson007** [comment]
Also add info how to request a namespace https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#naming

**Comment by samccann** [comment]
This should be in the dev guide, not the community/contributor guides. We can add pointers from the contrib guide to the dev guide.

**Comment by Andersson007** [comment]
> This should be in the dev guide, not the community/contributor guides. We can add pointers from the contrib guide to the dev guide.

OK, i'll take it into consideration, thanks

**Comment by Andersson007** [comment]
- [x] Create an MD version of the RST https://github.com/ansible/community-docs/pull/64
- [x] Compare with https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#developing-collections
- [ ] Publish on the Forum
- [x] UPDATE: or merge the docs if possible / acceptable instead

**Comment by Andersson007** [comment]
the path has been merged, I made the [announcement](https://matrix.to/#/!pMZboYFCScZJfXmOtH:ansible.im/$glrCETUPRFE3DRec_681yk4yTG6k4WurDBULSocoIpA?via=ansible.com&via=matrix.org&via=libera.chat).
So closing this as complete. @samccann thanks for your contribution!
