### ISSUE TITLE
[Epic] Meetup Organizer Toolkit

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-team#181]
Goal: The outcome of this issue is to develop a set of resources on the Ansible community site that meetup organizers can use to host successful events.

- [x] #188
- [x] #189
- [x] #190
- [x] #193
```[tasklist]
### Tasks
```

**Comment by samccann** [comment]
Need to also decide where this is published for community folks to find it. Could be a high-level link to docs and/or a downloadable item like a 'press kit' pdf, and link to a forum etc
This fits into the 'evangelist' persona and a way to make their lives easier. Should be visible and easy to find.

Existing resources (possibly outdated) - https://www.ansible.com/community/events/ansible-meetups

**Comment by samccann** [comment]
@anweshadas @oraNod - two options here for tracking progress:
 - use the checklist in the description and just check items as they complete
 - convert each checklist item into an issue. If you hover over the right end of each checklist row, you'll see a circle with a dot. That converts the checklist into an issue.

Which is your preference?

**Comment by samccann** [comment]
ps I can convert the checklist into issues but wanted to verify that's what you all want (including @leogallego as well).

**Comment by samccann** [comment]
@anweshadas - if an item is checked off above, then the issue should be closed as well to show it's done.

**Comment by leogallego** [comment]
> ps I can convert the checklist into issues but wanted to verify that's what you all want (including @leogallego as well).

Sorry @samccann missed this one. +1 to the checklist + linked issue (which seems to be a 3rd and the current option :D)

**Comment by samccann** [comment]
@leogallego these have been converted to issues. Each item in the checklist above is a separate issue.

**Comment by samccann** [comment]
Moved https://github.com/ansible-community/community-team/issues/191 to the website epic as it's applicable for meetups, conferences, and other events.

**Comment by samccann** [comment]
- [x] https://github.com/ansible-community/meetup/issues/11

**Comment by samccann** [comment]
Closing this epic as done. The final linked issue is not on the roadmap until next year.
