### ISSUE TITLE
Create central, shared events calendar available to the community

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#191]

**Comment by anweshadas** [comment]
Can we have a calendar section in the new website? Where we will be listing all the events happening in the different parts of the world in the Ansible community. For that the meetup organizers must have the rights/access to the calendar to edit the events.  Now the question is should we do have calendar in the website or in the central hub for the community? @oraNod @cybette @leogallego @GregSutcliffe

**Comment by cybette** [comment]
Looks like Nikola has an [iCal plugin](https://plugins.getnikola.com/v7/ical/) that we can perhaps use, and with this meetup organizers can submit event iCals as PRs.

Another option is to have a meetup category in the new forum where people with enough access level can add events, and embed that in the website.

I would also differentiate (separate calendars) between meetups and conferences.

**Comment by GregSutcliffe** [comment]
I agree on having a calendar of some kind, but I would place it as phase 2, after the MVP. Good to log it here so we don't forget though!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cybette** [comment]
Agree for phase 2. In addition I think it falls under the general website initiative and not Meetup organizer toolkit, because the calendar will be useful for organizers as well as attendees, and used for other events/conferences in addition to meetups. It is part of my plan for events page for the website.

**Comment by samccann** [comment]
moved to the web epic.

**Comment by oraNod** [comment]
@cybette This should be done now with the discourse event calendar right?

**Comment by cybette** [comment]
@oraNod yes, I love how it created itself :) (well not really, but through the power of the Discourse tooling and contributions from the community!)

Thanks!
