### ISSUE TITLE
Create followup guidelines for meetup attendees

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#193]
Establish a process or best practices for following up with meetup attendees and fostering community connections. (community working group)

**Comment by anweshadas** [comment]
We will be using the following for feedback 

- template provided by meetup.com
- email the attendees
- leave message at meetup.com's comment section

Included them in the Toolkit.

**Comment by samccann** [comment]
@anweshadas this is marked as done in the epic issue. Can we close this as done then?

**Comment by anweshadas** [comment]
@samccann closing this issue.
