### ISSUE TITLE
Create on-boarding document

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#21]
Create on-boarding document

**Comment by Andersson007** [comment]
Started a draft

**Comment by Andersson007** [comment]
Started a google doc. I'll add paragraphs one by one.

**Comment by Andersson007** [comment]
- [x] Add a section about the process of collaborating with community when releasing; elaborate on what i put in my on-boarding draft and create a section on our team's pages. (out of my responsibilities now, so marked it as done)
- [x] Add a section about handling collection requests based on  https://github.com/ansible-community/community-team/issues/37#issuecomment-1239092609
- [x] Add GHA vs AZP https://gitlab.cee.redhat.com/ansible/community/-/merge_requests/51
- [x] Add WG creating info based on https://github.com/ansible/community/issues/670#issuecomment-1301770051 see also https://github.com/ansible/community/issues/670#issuecomment-1309889059
- [x] Add the following that was moved out from https://github.com/ansible/community/blob/main/WORKING-GROUPS.md: Done with https://gitlab.cee.redhat.com/ansible/community/-/merge_requests/52

```
Process for Ansible Staff
===================

Once we have enough information, we will set up the following infrastructure:
* A Matrix channel
* [If required] An IRC channel on Libera.Chat named "#ansible-yourgroupname", properly registered and op'd;
  * `*!*@ansible/owner/*    +AORefiorstv`
  * `*!*@ansible/staff/*    +Oo`
  * Group Contact set - via Jimi-C
* github.com/community
  * Wiki new page and link from [1](https://github.com/ansible/community/wiki/_Sidebar/_edit) & [2](https://github.com/ansible/community/wiki/Home/_edit) and 
   A label in the issue tracker to identify issues/PRs for your working group;
* If the working group is created to work on a subset of content of a repository containing `.github/BOTMETA.yml` and having the bot running:
  * Add new label(s) to the repository
  * Add the related `labels:`, `keywords:` and `team_<wg_name>:` to `.github/BOTMETA.yml` (ensure set for module, module_utils, docs_fragments, integration tests, unit tests)
  * Update [Collection Bot](https://github.com/ansible-community/collection_bot/blob/main/ansibullbot/triagers/plugins/community_workgroups.py) to know about new Working Group
* Publicise
  * Internal Email & Slack
  * Matrix [#community:ansible.com](https://matrix.to/#/#community:ansible.com)
  * [Changes impacting Contributors](https://github.com/ansible/community/issues/346)
  * [The Bullhorn](https://github.com/ansible/community/issues/546)
  * Google Groups: `ansible-project` & `ansible-devel`
```

**Comment by GregSutcliffe** [comment]
@Andersson007 

see also:
- https://github.com/ansible/community/issues/671
- https://github.com/ansible/community/pull/668

**Comment by Andersson007** [comment]
done. Available on https://ansible.pages.redhat.com/community/onboarding/welcome.html
