### ISSUE TITLE
EE community feedback, issue 1

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#234]
By Felix, to take into consideration. Relates to https://github.com/ansible-community/community-team/issues/230

> does anyone know of good (and small) base images that can be used for EEs with ansible-builder 3.0.0? https://ansible-builder.readthedocs.io/en/stable/definition/ mentions [registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest](http://registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest), but you need an account to pull that image
> 
> [Execution Environment Definition — Ansible Builder Documentation](https://ansible-builder.readthedocs.io/en/stable/definition/)
> Ansible Builder Documentation Execution Environment Definition Edit on GitHub Execution Environment Definition  The execution environment (EE) definition file supports multiple versions.
> [andersson007_ (@andersson007_:matrix.org)](https://matrix.to/#/@andersson007_:matrix.org)
> : ^ could also be useful for https://github.com/ansible/community-docs/pull/60, having some example that can be run without being a RH customer / having an RH account would be really useful
> 
> [[WIP] execution environments: add EE overview page by Andersson007 · Pull Request #60 · ansible/community-docs](https://github.com/ansible/community-docs/pull/60) - GitHub
> Fixes ansible-community/community-team#232 execution environments: add EE overview page
> the https://quay.io/repository/ansible/ansible-runner images are now over a year old
> 
> [Quay](https://quay.io/repository/ansible/ansible-runner)
> Quay is the best place to build, store, and distribute your containers. Public repositories are always free.
> (and no idea whether it actually makes sense to use them with the ansible-builder v3 format)
>

**Comment by Andersson007** [comment]
https://github.com/ansible-community/community-team/issues/230#issuecomment-1553461393

**Comment by nitzmahone** [comment]
Just some points of comparison on a basic 3.0-built EE def that uses Python 3.9, ansible-core==2.15.0, ansible-runner==2.3.2, and no collections or external Python/system deps added (roughly comparable to the old `ansible-runner` image):

| Base Image       | Base Size (MB) | Demo EE Size (MB) |
|------------------|----------------|-------------------|
| ubi9/ubi-minimal | 97             | 187               |
| ubi9/ubi         | 217            | 269               |
| ubi8/ubi         | 215            | 310               |
| fedora:38        | 196            | 370               |
| centos:stream9   | 160            | 212               |
| centos:stream8   | 225            | 321               |


Note that even the heaviest of these is still a vast improvement over the 816MB of `quay.io/ansible/ansible-runner:latest` :laughing:

**Comment by felixfontein** [comment]
https://github.com/ansible/ansible-builder/pull/544 replaces the base image in the example (and adds some more as comments, including the original one).

**Comment by felixfontein** [comment]
Some PRs where I switched existing EE test workflows for collections to ansible-builder 3.0.0:
- https://github.com/ansible-collections/community.crypto/pull/606
- https://github.com/ansible-collections/community.docker/pull/630
- https://github.com/ansible-collections/community.dns/pull/142
- https://github.com/ansible-collections/community.hrobot/pull/80
- https://github.com/ansible-collections/community.routeros/pull/171
- https://github.com/ansible-collections/community.sops/pull/142

**Comment by samccann** [comment]
@Andersson007 : not sure if you captured this in an issue somewhere or not, but seems @felixfontein's use of EES in collection tests seems a good community use case we want to have in the EE docs 'somewhere'.

**Comment by Andersson007** [comment]
As we introduced community-ee-minimal (280MB) which can be freely used, closing the issue. Thanks everyone!
