### ISSUE TITLE
Define Execution environment documentation location and structure, move the docs

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#239]
Sub-task of https://github.com/ansible-community/community-team/issues/230

Execution environment documentation structure.

##### 1. Fully EE related (cannot be used for anything else):

- Ansible Builder: https://ansible-builder.readthedocs.io/en/stable/, documentation lives in https://github.com/ansible/ansible-builder/tree/devel/docs

##### 2. Multifunctional tools (can use EE but can be used for doing other kinds of tasks):

- Ansible Navigator: https://ansible-navigator.readthedocs.io/, lives in https://github.com/ansible/ansible-navigator/tree/main/docs and **uses the MD format** !
- Ansible Runner: https://ansible-runner.readthedocs.io/en/stable/, lives probably in https://github.com/ansible/ansible-runner/tree/devel/docs
- Ansible SDK: https://ansible-sdk.readthedocs.io/en/latest/intro.html#local-execution // https://github.com/ansible/ansible-sdk/tree/main/docs
- Ansible AWX/Controller: https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html // in the private ansible/product-docs repo
- _add more if i forget_

#### Questions to discuss:

UPDATED: added `readthedocs`

##### 1. Should all the tools' docs live in one location, i.e. on `readthedocs`?

- Pros:
  - Everything lives in one place which feels like a consistent UX and users don't need to jump between sites, the pages have the same style, etc.

- Cons:
  - Add your concerns

##### 2. The structure can be:
 
- shared-domain/builder: I think as ansible-buider is an entity unseparable with EE, builder's doc along with all general EE overviews and how-to's may live there (just an idea, maybe wrong: maybe we should put EE overview somewhere else) 
- shared-domain/runner
- shared-domain/navigator
- ...

Tasks to take into consideration:
- Should we convert MDs to RST at least for Navigator's docs?
- <Add your concerns>

This is important and pretty urgent as I've written the [first docs](https://github.com/ansible/community-docs/pull/60/files) and we need to put them somewhere to make it available for the community. If we're OK with having it on readthedocs, the plan can be **for now**:
1. We put the [EE overview page](https://github.com/ansible/community-docs/pull/60/files) in builder's doc
2. While we're deciding on moving builder's/runner's/navigator's docs to a shared domain, the EE overview page will contain refs to the current sites
3. We'll replace builders introduction page with EE overview page)
4. When we have all the docs in place and updated, we can mention EE across other ansible docs (like ansible/collections user guides) putting references to the EE overview page.

Ideas?

**Comment by Andersson007** [comment]
cc @oraNod @samccann @Spredzy @felixfontein

**Comment by oraNod** [comment]
@Andersson007 LGTM but perhaps "ee" themselves are too narrow for the url context. I'd be more in favour of something like `docs.ansible.com/how-to/` with entry points for different scenarios.

The how to's could be like the journey milestones we have today in terms of layout/presentation on the screen. The key difference is that how to's directly guide the user through an end-to-end scenario composed of a set of tasks that is centered around a piece of technology, rather than a persona journey.

In any case I totally agree with a separate url context so that `docs.ansible.com/ansible/index.html` remains scoped to the package docs (what you get with `pip install ansible`).

**Comment by oraNod** [comment]
@Andersson007 There is another part of your issue that my previous comment didn't address, specifically putting all tool docs under `docs.ansible.com`. Inline with what I was saying there, I feel like that subdomain belongs to the community and see it as a project that we grow and develop in a more sustainable way.

Going the other way (i.e. adding project docs to `docs.ansible.com` ) leads to more technical burden.

**Comment by Andersson007** [comment]
>Going the other way (i.e. adding project docs to docs.ansible.com ) leads to more technical burden.

@oraNod thanks for the input! Yeah, I'm not an expert in the underlying process and I think having the subprojects' docs in another location like readthedocs SGTM.
I'll update the issue description correspondingly, thanks!

**Comment by samccann** [comment]
I'm finding it difficult to separate this issue from https://github.com/ansible-community/community-team/issues/243 as there is considerable overlap.

#1 and #2 above -I think we've decided that yes, all projects will eventually move to readthedocs/foo etc. As Don mentioned, the how-to guides would live on docs.ansible.com/howto or some such url.
MD vs rst - no, we shouldn't change what a project has chosen to write in.


So going just on where EE documention should live:
- we likely cannot move most of what exists for EEs today. Each project has a legitimate reason to mention EEs and those should stay in some form.
- EE scenario/how-to guide - we haven't defined this space well enough yet so can't respond on where the source should live, but my nickel is all how-tos will be unversioned and thus should be separate from `ansible/ansible-documentation` as that one should be package docs, and howto guides are not part of package docs.
- 
- Existing overview and tutorial, as some comments in https://github.com/ansible-community/community-team/issues/243 suggest, the tutorial isn't full a tutorial or a how-to guide. I'll post comments in that issue and save this one for the general where should source files be, where should it publish, and what to do about other projects that have EE information.

**Comment by Andersson007** [comment]
@samccann i would name it not `tutorial` or `how-to` but rather a `Quick-start guide`.
https://medium.com/make-it-clear/the-importance-of-quick-start-guides-26ab7b1cf0df

**Comment by Andersson007** [comment]
Closing as done, thanks everyone!
