### ISSUE TITLE
Tidy up project in community-topics, re-arrange it to track decision implementation progress

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#24]
Relates to https://github.com/ansible-community/community-topics/issues/122

As the [Community Topics project](https://github.com/orgs/ansible-community/projects/2/views/5) is not used to track discussion progress anyway, we (the Community) decided to use it to track the decision implementation progress.
- [ ] Create columns Backlog/TODO, In progress, Done
- [ ] Go through all the topics including the closed ones
- [ ] Add topics that require actions to be done to the board
- [ ] Announce the board

**Comment by samccann** [comment]
Closing since our goal now is to close community-topics in favor of the forum.
