### ISSUE TITLE
Ansible community day, Berlin, September 2023

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#304]

**Comment by cybette** [comment]
Wednesday, September 20, 2023
in Berlin, Germany (tentatively c-base)
the day before [Matrix Community Summit](https://summit2023.matrixmeetup.de/conference/)

CFP and Registration coming soon!

**Comment by cybette** [comment]
Details in the Ansible forum https://forum.ansible.com/t/ansible-community-day-berlin-2023/19/4
