### ISSUE TITLE
Ansible contributor summit, Durham, October 2023

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#305]

**Comment by cybette** [comment]
Thursday, October 19, 2023
in Durham, NC, USA (tentatively Durham Convention Center/Caktus Group)
the day after [DjangoCon talks](https://2023.djangocon.us/), on their first Sprint day

Registration info coming soon!

**Comment by cybette** [comment]
Details in the Ansible forum https://forum.ansible.com/t/ansible-contributor-summit-durham-2023/28

**Comment by Spredzy** [comment]
@cybette should we close this one ?

**Comment by cybette** [comment]
Yep this can be closed, thanks.
