### ISSUE TITLE
Create galaxy_collection scenario guide

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#310]
The goal is to turn the [galaxy collection](https://github.com/ansible/galaxy_collection/tree/devel) embedded module/role documentation into a series of ‘how to’ sections that are added to the galaxy AH docs at 
https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/

Add a new guide here, something like “Galaxy_collection scenario guide”:
https://github.com/ansible/galaxy_ng/tree/master/docs/usage_guide

Document the workflows with examples that use the collection modules and roles.  This will be an epic that has multiple sub-issues to split up the work across different community writers. As these writers are not Ansible experts, we will strive to get the documentation set up, but  the actual examples will need to be provided by technical reviewers. We’ll copy existing examples where we find them in the source collection but can’t prove their accuracy or usefulness so to speak.

**Comment by samccann** [comment]
New files to add to this  new guide are as follows:

- How to authenticate to Galaxy
     - [create an authentication token](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_token.py#L56-L60)
     -  [authenticate to Galaxy](https://github.com/ansible/galaxy_collection/blob/devel/playbooks/testing_playbook.yml#L22-L30)
     -  [deauthenticate from Galaxy](https://github.com/ansible/galaxy_collection/blob/devel/playbooks/testing_playbook.yml#L22-L30)
- How to create an ansible.cfg file 
    - [set list of Galaxy servers](https://github.com/ansible/galaxy_collection/blob/devel/tests/playbooks/ah_configs/ah_ansible_config.yml#L2C1-L6)
    - [set certs for Galaxy servers](https://github.com/ansible/galaxy_collection/blob/devel/tests/playbooks/ah_configs/ah_ansible_config.yml#L7-L13)

- How to create or delete a namespace from Galaxy
	- [Create the namespace (with variables set accordingly)](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_namespace.py#L91-L103)
	- [rename a namespace](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_namespace.py#L91-L103) - add new_name parameter
	- [delete a namespace](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_namespace.py#L91-L103) - add state parameter and set to absent

- How to work with collections in Galaxy
	- [add  a collection](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_collection.py#L92-L96)
	- [remove a collection](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_collection.py#L99-L104)
	-  [publish a collection](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_collection.py#L92-L96) - add ah_auto_approve parameter and set to true.

- How to work with Execution Environments
	- [add  an  Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_registry.py#L114-L121)
	- [remove an Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_registry.py#L134-L140)
	- [sync an Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_registry_sync.py#L55-L58)
	- [indexing an Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_registry_index.py#L62-L66)
	- [add an Execution Environment repository](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_repository.py#L113-L124)
	- [remove an Execution Environment repository](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_repository.py#L105-L111)
	- [sync an Execution Environment repository](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_repository_sync.py#L55-L58)
	- [add an image to an Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_image.py#L82-L88) - change state: absent to state:present
	-  [remove an image from an Execution Environment registry](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_image.py#L82-L88)
	- [tag an image](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_ee_image.py#L58-L68)

- How to work with users and group permissions in Galaxy
	- [create a user group with permissions](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_group.py#L47-L54)
	- [delete a user group](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_group.py#L55-L61)
	-  [create a user and add to a group](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_user.py#L105-L115)
	- [delete a user](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_user.py#L97-L103)
	- [create a role of group permissions](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/ah_role.py#L76-L87)
	- [add role to a group](https://github.com/ansible/galaxy_collection/blob/devel/plugins/modules/group_roles.py#L105-L128)

- How to fully configure Galaxy
	 ([dispatch role](https://github.com/ansible/galaxy_collection/tree/devel/roles/dispatch#playbook-examples) – include warning it’s for advanced users)
	- This role can set up the ansible.config, create namespaces and  upload collections, set up EE 	registry and upload, and manage users, groups and permissions.

note – ee_namespace role deprecated in favor of ee_repository so will not document that role

Questions:

1. is this the appropriate outline (aka does it cover the main uses of this collection)
2. is there reason to also document using the collection w/o roles?

**Comment by sean-m-sullivan** [comment]
How to add an ansible.cfg file to AH

?? where are we adding a file to the hub, we create them, have a template for use for connecting. Just think we need a better title.

**Comment by sean-m-sullivan** [comment]
Needs some context, but here is another repo of examples for creating things
https://github.com/PacktPublishing/Demystifying-Ansible-Automation-Platform/tree/main/ch09

**Comment by samccann** [comment]
Thanks @sean-m-sullivan . Updated the ansible.cfg title. It's basically this role - https://github.com/ansible/automation_hub_collection/tree/devel/roles/ansible_config

**Comment by sean-m-sullivan** [comment]
Looks good, I think its more direct, built that role back before execution environments, or we had so many that auto create it in the hub. :)

**Comment by samccann** [comment]
@sean-m-sullivan - do you recommend we use the roles in this collection, or the modules directly?

Also, should we mention at the end of 'creating ansible.cfg"  the user should include that with their execution environments (and point them to the builder guide or getting started with EEs guide?)

**Comment by rochacbruno** [comment]
@samccann for galaxy docs it would be better to have documentation about setting things up (like the cfg, auth variables) and then docs covering modules directly.

Also, we are about to rename some of the modules, so I suggest waiting this little refactoring to be done.

**Comment by Dule-martins** [comment]
@samccann are we still waiting as suggested by @rochacbruno?

**Comment by rochacbruno** [comment]
@Dule-martins we have decided about the collection name, now it is going to be release as `galaxy.galaxy`

We are also going to rename all the modules, right now modules are prefixed with `ah_` as in `ah_namespace` and we are planning the refactor to remove the `ah_` prefix then module will be in that case just ` namespace`

That's ok to work on the docs with the current namings and we find/replace later.

wdyt @sean-m-sullivan ?

**Comment by Dule-martins** [comment]
Set to work on it, then

**Comment by sean-m-sullivan** [comment]
I think that works, sounds like a plan

**Comment by samccann** [comment]
### Working in the galaxy_ng repo
This project has a couple of extra requirements that aren't on ansible/ansible or ansible/ansible-documentation so adding a few notes there to help contributors along.

#### All commit messages must include JIRA issue or No-Issue
See the [contributing guide](https://github.com/ansible/galaxy_ng/wiki/Contributing#preparing-pull-requests) for details. CI will fail if this is not present in each commit message. **It needs to be on its own line in the commit message with no extra whitespace or other text.** See example below.
For this project, the matching JIRA issue (an internal Red Hat tracking tool) is AAH-2420

So your commit messages should be something like the following:
`git commit -m "added foo docs" -m "Issue: AAH-2420"`

#### All commits must be signed
This one takes a few steps to set up if you don't already have git and github configured for signing.
1. [Generate a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
2. [Add the GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account) to your GitHub account.
3. [Tell git about your gpg key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key).

If you set this up globally, then all commits will be signed for all repos you work with. If you want to only sign commits for the galaxy_ng repo, use the -S command with git:
`git commit -S -m  "Added foo docs" -m  "Issue: AAH-2420"`

### Other things to keep in mind
Since this collection will have different upstream vs certified collection names, we want to avoid using the fully qualified collection name, and just use the module or role names. This will show up mostly in examples.

**Comment by samccann** [comment]
@Dule-martins : I created a smaller issue to get started on this work. See https://github.com/ansible-community/community-team/issues/318.

**Comment by samccann** [comment]
@sean-m-sullivan @rochacbruno : I updated the [outline comment](https://github.com/ansible-community/community-team/issues/310#issuecomment-1638724598) with links to the examples to include. Can you check to see if you agree/disagree? I think once the PRs come in, we can have y'all adjust the examples with something more realistic.

**Comment by sean-m-sullivan** [comment]
It looks good, it should contain most of everything, However this section we need to go over how we want to do things
How to work with users and group permissions in Galaxy

I just uploaded a new role/module for this to work in 2.4, and in many cases it will work in 2.3, but what is listed is the process for a 2.2 server.

**Comment by Dule-martins** [comment]
@samccann got you!

**Comment by samccann** [comment]
Hi @Dule-martins - any update on this?

**Comment by Dule-martins** [comment]
> Hi @Dule-martins - any update on this?

I'm sorry for replying to you late on this, I'm currently on that, so I'll give you this update a few hours from now.

**Comment by Dule-martins** [comment]
I have succeeded in adding a signature to my commit and letting my Git bash know as well, but I added it globally and was thinking what if I want to only sign commits for the galaxy_ng repo? Then I try to use the `-S` command with git:
`git commit -S -m  "Added foo docs" -m  "Issue: AAH-2420"`
 But got an error message
> > Hi @Dule-martins - any update on this?
> 
> I'm sorry for replying to you late on this, I'm currently on that, so I'll give you this update a few hours from now.

**Comment by samccann** [comment]
@Dule-martins hmm I'm not sure. signed commits are new to me as well and I just enabled them globally. How about asking on the matrix docs channel and posting the error you get there?

**Comment by Dule-martins** [comment]
Alright @samccann thanks for helping
