### ISSUE TITLE
Create docs scaffolding for galaxy collection.

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#318]
This is part of https://github.com/ansible-community/community-team/issues/310.

Before creating a PR for this, see https://github.com/ansible-community/community-team/issues/310#issuecomment-1677887863 for details on how to set up your repository and GitHub to work with the galaxy_ng repository. See https://github.com/ansible/galaxy_ng/wiki#contributing-to-galaxyng for complete contributor details.

This issue is to add a folder under `usage_guide` and add a few files as follows:

```
docs/usage_guide/
    galaxy_collection/
        installing.md
        authenticating.md
        creating_ansiblecfg.md
        namespace.md
        collections.md
        execution_environments.md
        users_groups.md
        full_configuration.md
```

**Comment by samccann** [comment]
These files will start out empty, but once in place, it allows multiple people to fill in the files in parallel PRs.

**Comment by Dule-martins** [comment]
Alright if I encounter any challenge I'd be screen your name for help 😎😎

**Comment by samccann** [comment]
Cool thanks! Remember the set up is a bit different than the other Ansible repo you've worked in. See https://github.com/ansible-community/community-team/issues/310#issuecomment-1677887863 for details.

**Comment by Dule-martins** [comment]
I have succeeded in making sure all commits are signed, I will send in a PR to address this issue tomorrow. 
Will these files be an empty file? @samccann

**Comment by samccann** [comment]
@Dule-martins yes they are empty files. The goal is to have the files there, and then individual people can populate each file w/o having merge conflicts (I hope :-)
