### ISSUE TITLE
Create place for event/meetup slide sharing

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#326]
We would like to have a place where people who present at Ansible events or meetups can upload their slides to share with the community.

**Comment by samccann** [comment]
As part of archiving the ansible/community repository, we may create an ansible-community/presentations repo to hold these presentations.

There are already some placeholder locations for individual meetups at https://github.com/ansible-community?q=meetup&type=all&language=&sort= so closing this issue as a duplicate of those efforts.

**Comment by gotmax23** [comment]
How about a forum tag or category? The forum allows attachments and links and provides a place for discussion.

**Comment by samccann** [comment]
Since this is part of the repo archive discussion, I added it here so we can continue the conversation in one place:
https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928/15

thanks!
