### ISSUE TITLE
news-for-maintainers to the forum

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#367]
news-for-maintainers migration to the forum plan:

- [x] create the `news-for-maintainers` tag: it's publicly visible but only Core and SC are allowed to use it.
- [x] create an URL for a pre-filled topic using the `news-for-maintainers` tag and `Project Discussions` category
- [x] create a group called `Collection Maintainers` Created https://forum.ansible.com/g/CollectionMaintainer
  - [x] fill up
  - [x] add the link for pre-filled topic template we created before
  - [x] add autosubscription for the tag
- [x] reach out to core folks (waiting for feedback)
- [ ] announce in Bullhorn asking collection maintainers / contributors to subscribe
- [ ] announce in news-for-maintainers that all new announcement will happen on the forum, ask them to update their READMEs of they refer to news-for-maintainers
- [ ] update news-for-maintainers readme / archive the repo
- [ ] core starts using the forum
- [ ] update collection_template/README.md
- [ ] update all the docs on docs.ansible.com
- [ ] announce in news-for-maintainers again in a month or so to remind people to subscribe

**Comment by samccann** [comment]
See - https://github.com/ansible/ansible/issues/82251  for current status.

**Comment by Andersson007** [comment]
core don't want to use neither forum nor news-for-maintainers (only for AZP container updates announcements). closing:(
I hope it won't cause big issues jeopardizing our collections communities.

**Comment by gundalow** [comment]
I believe that blocker is based on old information. Give me a few days to talk with some folks.

**Comment by jimi-c** [comment]
@Andersson007 yes, the Core team previously had a policy of for team members to have "at-will" use of the forum (we did not require the team to engage there, nor did we discourage it), however we are now actively working with the Steering Committee and the Community team to move to the forum as our primary source of communication. As such, going forward that should not be a concern for keeping this issue open.

**Comment by Andersson007** [comment]
@jimi-c do i understand it correctly that the core team is going to interact with collection maintainers via the forum?
If yes, it's cool, though the main issue in the context of news-for-maintainers is that the core team announced that it would **stop publishing** CI and other updates impacting collection contributors and maintainers in principle.
It was announced in an [issue there](https://github.com/ansible-collections/news-for-maintainers/issues/69) and discussed in a linked discussion.

I can recap why it's important.
The core team was publishing changes impacting collection maintainers and contributors
in the news-for-maintainers repository for more than 2 years and before that they published it in a dedicated issue.
We have many notes in our collection maintainer guidelines for maintainers about importance of those notification and a call to subscribe to the repo ASAP.
Now more than 130 maintainers are subscribed of around 100 collections included in the package.
This was the way to notify maintainers about changes primarily impacting collections CI.
The result of making those changes in most cases if not addressed is failures in test runs in pull requests *unrelated* to the PRs themselves.
When it happens PR authors get confused which causes an unpleasant experience of figuring out what's wrong in vain.
Maintainers, even if they missed notifications about the changes, can take a look at emails
and quickly figure out that some changes were made and how to fix it.
If there are no more notifications in their mailboxes, maintainers will be confused, especially not very experienced ones.
I, as a maintainer of several collections, fully agree with @felixfontein and [his comment](https://github.com/ansible-collections/news-for-maintainers/discussions/70#discussioncomment-9014075) in the related discussion that "it's a really bad idea [to stop publishing the changes], and it feels very unfriendly especially towards community collection maintainers.". He know what he's talking about being a maintainer of many top collections.
Now, @felixfontein sometimes posts messages on the forum about CI changes he derives from CI failures on his own..
So considering the above, I believe that keeping the changes in core impacting collections CI posted in news-for-maintainers or forum is very important for community and Ansible success.

So if the core team reverts the decision not to post the announcements, we could proceed with moving them to the forum, otherwise there would be not much to move.
I'd be grateful for any feedback.
