### ISSUE TITLE
Collection requirements: add requirements.txt and bindep.txt for EE purposes

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#372]
https://forum.ansible.com/t/collection-inclusion-requirements-add-requirements-txt-and-bindep-txt/2611
https://github.com/ansible/ansible-documentation/pull/871

a sub-task of https://github.com/ansible-community/community-team/issues/230

- [ ] If approved by SC, after merging also the PR, update https://github.com/ansible-collections/overview/blob/main/collection_checklist.md
- [ ] Announce via Bullhorn, Forum and news-for-maintainers if accepted.

**Comment by samccann** [comment]
Fixed by https://github.com/ansible/ansible-documentation/pull/871
