### ISSUE TITLE
[epic]Accessible documentation for docs.ansible.com

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#40]
The Ansible community aims to be the most inclusive it can potentially be. Inclusion encompass several areas, one of them being offering tools and resources that are usable for people of all abilities.

As such we aim to offer a documentation that is accessible to as many people as we can. Accessibility is not an after thought but something that needs to come first as we design and write our documentation.

This issue is not a one-actionable item, but aim to list the issues we need to get done before being able to label ourselves as providing an accessible documentation

**Plan of actions**:

- [x] #41
- [x] #42
- [x] #43
- [x] #44

**Comment by GregSutcliffe** [comment]
Need to think about this in the context of other changes to docs.ansible.com as part of the product migration to redhat.com
