### ISSUE TITLE
[Task] Cross-project contributor exp: Define comprehensive, ready-to-use docsite template in project_template

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#422]
task for epic https://github.com/ansible-community/community-team/issues/416

- [x] #423
- [x] Find a currently working project on readthedocs with docs preferably in MD format to use as an example: https://github.com/ansible/ansible-navigator/tree/main/docs
- [x] Restructure / update the docs/ in project_template to create a comprehensive ready-to-use docsite template, think of what to have in the README template vs docsite template
- [ ] ...

**Comment by Andersson007** [comment]
@oraNod @samccann i strongly believe we need to render https://github.com/ansible-community/project-template/tree/main/docs on readthedocs, can we arrange it please? If you're OK, I could create an issue

**Comment by oraNod** [comment]
@Andersson007 Yes, please create an issue in the repo. We'll need an mkdocs config, readthedocs config, and a noxfile with a build check for ci. I can add some more detail to the issue so we can announce it at the DaWGs meeting and offer it up to contributors who might be interested.

**Comment by Andersson007** [comment]
The PR has been merged and the jira task has been closed, closing this one, thanks everyone!
