### ISSUE TITLE
[Task] Cross-project contributor exp: Auto-publishing of the project_template repo docs content on readthedocs

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#423]
Task of epic https://github.com/ansible-community/community-team/issues/416

Relates to https://github.com/ansible-community/community-team/issues/422 and https://github.com/ansible-community/community-team/issues/421

The idea is to publish https://github.com/ansible-community/project-template/tree/main/docs content on readthedocs.

Purpose:
- As the docs will be used as a template for other real project, it should be available for its potential users (project maintainers) in the website form.
- It should also be available for its maintainers to better understand its look for readers
- There'll be examples and links to things like Bullhorn, different general guidelines like doc guide, etc., so there's also an educational purpose.

Please arrange the automatic publishing under readthedocs.

**Comment by samccann** [comment]
autopublishing on pr merge now working - https://ansible.readthedocs.io/projects/ansible-project-template/en/latest/
