### ISSUE TITLE
[Epic]Strategize how to grow active contributors 2023

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#46]
The Ansible community aims to be a healthy, inclusive, new-comer friendly, long live community. A community is made of people, people come, join a community, contribute / participate and eventually move on as their lives permit.

The Ansible community is always looking for new contributors to bring their contributions to the Ansible journey.

This issue is not a one-actionable item, but aim to list the issues we need to go through to go and capture new contributors

**Plan  of action:**

  * [x] #47
  * [x] #48
  * [x] #49
  * [x] #50

**Comment by samccann** [comment]
Closing since the only remaining item is another epic and it gets confusing to have two of them basically saying the same thing.  We are also using other epics to describe how we grow the contributors including the instruqt labs, meetups, and community website.
