### ISSUE TITLE
Provide current state of the community activities (Github Contributions, Chat activities, ...)

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#47]
Before going out and "capture new contributors" we need to understand the current state of our community. How active it is on Github ? How active it is on IRC/Matrix ? How active it is on mailing list ? How active it is on social events like Meetups ?

Having visibility in those data can help see what is it we are doing  right and help isolate the gap we have to attract a new set of contributors.

**Expected Results**

In order to close that issue, we need to have a way to visualize current community "health" over time (engagement, activity, ...). This could take the form of HTML report that could be shared.

**Comment by Spredzy** [comment]
@GregSutcliffe this ticket is to highlight the work you've been doing with the Orbit report. Ideally they should be publicly available (already the case IIRC), but having a way to people to route to them would be great. Landing page, entry in docs.ansible.com, something else ...

**Comment by samccann** [comment]
I think this is done by https://ansible.github.io/community/posts/state_of_the_community_2023.html  

@GregSutcliffe @Spredzy  - I'll close this as done if y'all don't see anything else for this one...
