### ISSUE TITLE
Discuss a different approach to email-based communication

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#48]
Mid 2021, the Ansible Community team provided Matrix as an alternative to IRC, allowing user to choose which protocol they wanted  to use to be able to communicate for instant messaging (IM). The intent behind this move was well described in @GregSutcliffe 's [blog post](https://ansible.github.io/community/posts/matrix_and_ansible.html)

This sentence summarized the reason of the move pretty well.

> The world turns, and we move with it. The way in which we communicate has evolved, as it always has, and periodically we must catch up if we want to attract new people to our community. Today, that means offering a place where new and existing contributors feel welcomed, safe, and valued, with a rich interface and a low barrier to entry. I want to help build that, because I fear that if we don’t, we will fade, and Ansible deserves better than that.

To follow up with what has been done for instant messaging, we should rethink our approach to email-based communication (mailing lists) and ensure we provide new contributors with a low barrier to entry (easy contributor experience) while still allow contributors to use the mailing lists.

**Expected Results**

Have a conversation and provide a path forward (or not with justification) on how to evolve our currently email-based communication system to a lower barrier to entry one new contributors might find it easier to use.

**Comment by samccann** [comment]
Discussion started at https://github.com/ansible-community/community-topics/issues/202
