### ISSUE TITLE
Hacktoberfest - Prepare 2022 edition

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#49]
[Hacktoberfest](https://hacktoberfest.com/) is a yearly event that encourages people from all over the planet to contribute (in a meaningful way) to Open Source.

The goal is to provide easy enough, yet impactful issues to contributors that are not normally part of your traditional contributors circle.
Our commitment is to be engaged with them to ensure their contributions land in a timely fashion and they get the assistance they need.

**Expected Results**

  * Make sure `ansible/ansible` (and other repo under ansible org) have added the `hacktoberfest` topic in their description
  * Socialize on the bullhorn that we are participating to Hacktoberfest
  * Create a set of issues with the `hacktoberfest` label and clear explanation on what's exected
  * Organize ourselves (maybe a weekly triage meeting) during 4 weeks, to ensure we are on top of the contributions

**Comment by samccann** [comment]
docs coordination happening at https://hackmd.io/gNQ2TQW8T4ilcZc8JAM5fQ

**Comment by samccann** [comment]
docs issues at https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Adocs+label%3Ahacktoberfest+

**Comment by samccann** [comment]
Closed 36 docs issues during hacktoberfest.
