### ISSUE TITLE
[Epic] Community Community 2023

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#50]
In order to grow our community base, we should be thinking about how do we reach outside current Ansible community. How do we get people interested in contributing into one of the various ansible communities. An Ansible contributor is not meant to be only a python coder, there are various way that someone can engage with the various communities (Documentation, Release, People management - running meetings, getting people in touch - Infra, etc...).

The goal of this EPIC is to write, communicate and implement an Outreach program that will help get external to Ansible community contributors to be active contributors in our ecosystem

- [x] Create a community outreach plan
- [x] Share details and gather feedback from community
- [x] Implement plan :-)

**Comment by samccann** [comment]
@leogallego @anweshadas @cybette - this is an epic w/o a lot of details. Can you edit the description to create a good checklist of what we hope to do this year? Then I can turn them into subissues.

**Comment by cybette** [comment]
The Meetup organizers toolkit will fall under this initiative, as well as the rewards and recognition plan.

Other items off the top of my head:
- mentoring/academy program
- Community YouTube
- Community blog
- meetups and conferences (probably easier to track with meetup.com/discourse instead of on GitHub)
- The Bullhorn (it's ongoing but might reconsider tooling - e.g. alternative to mailchimp)

**Comment by anweshadas** [comment]
The event calendar (as @leogallego suggested) should it be under this as well?

**Comment by cybette** [comment]
> The event calendar (as @leogallego suggested) should it be under this as well?

For me that's part of meetups and conferences and "tracking" with discourse (which has calendar function)

**Comment by samccann** [comment]
Contributor summit and community day planning happening in July

**Comment by samccann** [comment]
Closing this as too broad an item. We have separate epics for most of these already
