### ISSUE TITLE
[Epic] Identify our communities and their respective needs

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#51]
The Ansible ecosystem has evolved a lot over the last few years. It has grown from mainly `ansible/ansible`  to a variety of ecosystems; to name a few we have : all the collections, `ansible/awx`, `ansible/galaxy_ng`, `ansible/ansible-lint`, `ansible/ansible-navigator`, etc...

While `ansible/ansible` and the collections are  well known by our community, the rest of the ecosystem is not as well known. The idea here is to reach our to those projects leads and  see how, where and when the Ansible Community team can help to drive-in more community contributions / presence where the  need arise

**Plan of action:**

  * [x] #52
  * [x] #53
  * [x] #54
  * [x] #55
  * [x] #56

**Comment by samccann** [comment]
Since we have identified internal champions, trimming this issue down to:
- gather feedback and share in a document.
