### ISSUE TITLE
Evaluate SEO impact and type of forum links to use

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#556]
https://forum.ansible.com/t/google-doesnt-seem-to-be-indexing-the-forum/1883/7

Is there anything we need to consider as we craft all these forum links in github?

**Comment by samccann** [comment]
Reading up on https://developers.google.com/search/docs/fundamentals/seo-starter-guide

**Comment by samccann** [comment]
Basic guidelines for good urls:
* [Use good text in the link](https://developers.google.com/search/docs/crawling-indexing/links-crawlable#write-good-anchor-text) For example, it's better to use 'use good text in the link`  than 'read this'.  
* Promote linking  internally within the site (aka forum). It helps people and search engines find related info.

**Comment by samccann** [comment]
Some examples of how to do this for matrix/irc links in github today:

###  For projects with a working group in the Forum:

Change:
```
The `#ansible-aws` channel on [irc.libera.chat](https://libera.chat/) is the main and official place to discuss use and development
```

To: 
```
The [AWS Working Group](https://forum.ansible.com/g/AWS) is the main and official place to discuss use and development
of the `amazon.aws` collection.
```

### For projects with no working group:
```
Click [Ansible Forum postgresql tag](https://forum.ansible.com/tags/c/project/7/postgresql) to discuss use and development of the `community.postgresql` collection.
```

**Comment by samccann** [comment]
@oraNod - I didn't find much about good google linking other than the stuff we already know. What do you think about the examples in https://github.com/ansible-community/community-team/issues/556#issuecomment-2206605151 ?

**Comment by oraNod** [comment]
@samccann I think that seems OK. Not much else to add there really other than making sure that forum urls are as descriptive as possible. I think you have this covered for the most part but it's something I learned while hacking on the website.

URLs like `AWS-working-group` are more descriptive than simply `AWS` for instance. I know it's probably too late to change that, just saying.

**Comment by samccann** [comment]
I'm guessing the url for a forum group is based on the (short) name given in the [new group](https://forum.ansible.com/g/custom/new) form. So yes, we can't go back and change existing ones afaik, but we can change the template to say make the name unique, not just 'awx' etc.

**Comment by samccann** [comment]
@GregSutcliffe ^^ just to be sure I'm not out in space on that prior comment...
