### ISSUE TITLE
Create a checklist for onboarding new projects to Ansible

### ISSUE THREAD

**Issue by Spredzy** [ansible-community/community-team#56]
We have some existing onboarding information for new projects. Update and create/add a checklist to cover things like matrix/forum, docs recommendations (rst vs md and theme).

**Comment by samccann** [comment]
TBD if we need a document to gather this detail or use the meetings/discussions we already have in place to keep communications open and gather needs in an ongoing basis

**Comment by samccann** [comment]
Further review, we could have a document checklist that includes things such as:

- guidelines on which github org to add a project to (ansible, ansible-community, etc)
- setting up matrix/irc and deciding on WG or async development
- Creating common files in repo (licence, contribute, code-of-conduct, readme) . Contribute should include chat channels
- (future) specific forum areas (category, tag)

**Comment by samccann** [comment]
Draft available at https://hackmd.io/_--vbKYOST60lNMs5w74IQ

**Comment by samccann** [comment]
Published - https://ansible.readthedocs.io/projects/project-onboarding/en/latest/
