### ISSUE TITLE
[Epic] Testing collections in the package

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#57]
The context:
- According to the [collection inclusion requirements](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html), collections to be a part of the Ansible Community package must pass sanity tests.
- If we our contributors have `red` CI runs against their PRs for unrelated reasons, it does not feel good at all

If we see the collections with red sanity CI, we could:
- In simple cases, fix the errors ourselves
- Create issues to fix
- If no response, raise the question about considering the collection unmaintained and remove it from the package

Issues:
- We (the community & the team) don't see which collections have sanity errors at the moment w/o going through the collections manually which is a bit problematic as we have ~120 included collections.

Questions:
- Is it really worth solving? Maybe we should just relax?

Possible solutions:
- Investigate if there are native solutions on GitHub (for GitHub action) / Azure Pilepines to see CI runs under a whole org. So an interested person can open 1/2 views and see red CI runs.
  - An issue can be that we have also collections out of RH orgs (ansible-collections org) but in third-party repo/orgs.
- Write a web app to show green/red CI runs in included collections
  - A possible downside: it can take a lot of time for implementation for uncertain (maybe little) value.
- Write a command line tool with will fetch all the included collections, run sanity tests, report errors.
  - It'll probably take much less time thфn developing of the web app but the value is still uncertain.

Relates to https://github.com/ansible-community/community-team/issues/9

We need to do:
- [x] #58
- [x] #59

**Comment by Andersson007** [comment]
another related issue https://github.com/ansible-community/community-team/issues/9

**Comment by samccann** [comment]
@Andersson007  - can you triage this issue and the two subissues? Basically:
- ensure they have enough detail so someone taking it on knows what to do
- set the size etc fields.

They are already in the 'improve ansible package' initiative. Thanks!

**Comment by Andersson007** [comment]
@samccann 
- I re-analyzed and re-formulated the task so that it can be understood not only by me:)
- I put `medium` size and impact as it's uncertain, I'll adjust it after completing p. 1 from https://github.com/ansible-community/community-team/issues/58

thanks

**Comment by Andersson007** [comment]
closing, let's leave the stuff to package release engineers, i.e. let them define the issues themselves
