### ISSUE TITLE
Testing Collections: identify issues

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#58]
To solve https://github.com/ansible-community/community-team/issues/57 we need to identify related issues we need to solve.
See the [main issue's description](https://github.com/ansible-community/community-team/issues/57) for the starting point.

- [ ] Contact contributors involved in inclusion/exclusion (at least mariolenz, gotmax23, felixfontein) what they think about it
- [ ] (if needed) Find related community topics (there are 1-2, IIRC) https://github.com/ansible-community/community-topics/issues. Maybe update it/closed it if irrelevant.
- [ ] (if needed) Get feedback from the community: create a topic + bullhorn

**Comment by samccann** [comment]
As part of this, we should also test and identify collection changes that break the docs build.
