### ISSUE TITLE
Collection inclusion: improvement

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#76]
The main issue is the low community activity in https://github.com/ansible-collections/ansible-inclusion/discussions/.

In order to fix it:

- [x] https://github.com/ansible-community/community-team/issues/75
- [x] https://github.com/ansible-community/community-team/issues/79
- [X] Get community ideas by creating a [community topic](https://github.com/ansible-community/community-topics/issues/152)
- [x] https://github.com/ansible-community/community-team/issues/78
- [x] Collect and analyze feedback
- [x] https://github.com/ansible-community/community-team/issues/77
- [ ] think of what can be automated and don't review a collection if the script doesn't pass
- [ ] update the inclusion guidelines with "buddy" (offer mentoring and going through the stuff together)

**Comment by samccann** [comment]
@Andersson007 does this look a good one to make the 'epic' for collection inclusion stuff we've been discussing offline?

**Comment by Andersson007** [comment]
@samccann I'd rather close this one and create another one instead
