### ISSUE TITLE
Collection Inclusion: make it visible on docs.ansible.com

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#77]
Collection Inclusion: make it visible on docs.ansible.com

Currently this type of contribution is not advertised on docs.ansible.com. Should be added to:
- [ ] https://docs.ansible.com/ansible/devel/community/contributor_path.html
- [ ] https://docs.ansible.com/ansible/devel/community/how_can_I_help.html#how-can-i-help
- [ ] https://docs.ansible.com/ansible/devel/community/contributions_collections.html#collections-contributions (to some of the docs)
- [ ] anywhere else?
- [ ] maybe to move [README's](https://github.com/ansible-collections/ansible-inclusion/discussions/) content to docs.ansible.com?
- [ ] maybe to move [overview's'](https://github.com/ansible-collections/overview) content to docs.ansible.com?

**Comment by samccann** [comment]
This  should be moved to ansible/ansible as it's a docs issue for those source files.

**Comment by Andersson007** [comment]
I would prefer keeping my tasks in one place:) I could create another issue (or a PR) in ansible/ansible later

**Comment by Andersson007** [comment]
closing as irrelevant
