### ISSUE TITLE
Steering Committee: merge stuff from one doc to Community Ambassadors spreadsheet

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#80]
- [ ] Merge Steering Committee related stuff from [Google doc](https://docs.google.com/document/d/1NhQqdAWH9co_WYjw6fbC6HBIuojNrPFW1qJWlOtHHYM/edit) to [Community Ambassadors spreadsheet](https://docs.google.com/spreadsheets/d/1EUbQE281XH662Upq2qeSWjEbvqgaI4z1nfZ_ZhmGMPI/edit#gid=0)
- [ ] Remove it from the doc

**Comment by samccann** [comment]
Closed by https://github.com/ansible-community/community-team/issues/71
