### ISSUE TITLE
ansible/community: update/close what should be

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#87]
Update docs in https://github.com/ansible/community
- [x] Update README
- [x] Update WORKING-GROUPS.md
- [x] Remove irrelevant WGs/meetings info
- [x] https://github.com/ansible/community/tree/main/meetings
- [x] https://github.com/ansible/community/pull/673
- [x] https://github.com/ansible/community/pull/680
- [x] https://github.com/ansible/community/pull/681
- [x] https://github.com/ansible/community/pull/683
- [x] https://github.com/ansible/community/pull/684
- [x] https://github.com/ansible/community/pull/686
- [x] contact folks to close/update open PRs https://github.com/ansible/community/pulls?q=is%3Aopen+is%3Apr
- [x] close the PRs where no response ^ or response to close
- [x] go through open issues https://github.com/ansible/community/issues

**Comment by samccann** [comment]
Closing this one out since we are archiving that repo now - see https://github.com/ansible/community/issues/707
