### ISSUE TITLE
Think about ways on how to make life of our contributors easier

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#94]
Think about ways on how to make life of our contributors easier.
The goal is to have a list of those things, discuss it with the team and the community.
Set goals for the following year.

**Comment by samccann** [comment]
@Andersson007 - we have work ongoing for new contributors etc, but do you see this as an effort to make existing contributors lives easier?  Do we want to reach out and ask existing contributors for bottleneck problems?  
Can you add more details here so we can triage etc?

**Comment by samccann** [comment]
we will create smaller issues as this one is too vague.
